# Generated by Django 2.1.3 on 2020-11-19 15:59

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201117_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.TextField(help_text='Friendly name', unique=True, verbose_name='Friendly name')),
                ('rules', djongo.models.fields.JSONField(default=[])),
            ],
        ),
        migrations.AlterField(
            model_name='openidrepository',
            name='authorization_endpoint',
            field=models.TextField(default='', help_text='', verbose_name='Authorization url'),
        ),
        migrations.AlterField(
            model_name='openidrepository',
            name='end_session_endpoint',
            field=models.TextField(default='', help_text='', verbose_name='Disconnect url'),
        ),
        migrations.AlterField(
            model_name='openidrepository',
            name='issuer',
            field=models.TextField(default='', help_text='', verbose_name='Issuer to use'),
        ),
        migrations.AlterField(
            model_name='openidrepository',
            name='token_endpoint',
            field=models.TextField(default='', help_text='', verbose_name='Get token url'),
        ),
        migrations.AlterField(
            model_name='openidrepository',
            name='userinfo_endpoint',
            field=models.TextField(default='', help_text='', verbose_name='Get user infos url'),
        ),
        migrations.AlterField(
            model_name='userauthentication',
            name='sso_forward_capture_content',
            field=models.TextField(default='^REGEX to capture (content.*) in SSO Forward Response$', help_text=''),
        ),
        migrations.AlterField(
            model_name='userauthentication',
            name='sso_forward_content',
            field=models.TextField(default='', help_text=''),
        ),
    ]
