# Generated by Django 2.1.3 on 2020-11-24 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20201120_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openidrepository',
            name='authorization_endpoint',
            field=models.TextField(default='', help_text='', verbose_name='Authorization url'),
        ),
        migrations.AlterField(
            model_name='openidrepository',
            name='end_session_endpoint',
            field=models.TextField(default='', help_text='', verbose_name='Disconnect url'),
        ),
        migrations.AlterField(
            model_name='openidrepository',
            name='issuer',
            field=models.TextField(default='', help_text='', verbose_name='Issuer to use'),
        ),
        migrations.AlterField(
            model_name='openidrepository',
            name='token_endpoint',
            field=models.TextField(default='', help_text='', verbose_name='Get token url'),
        ),
        migrations.AlterField(
            model_name='openidrepository',
            name='userinfo_endpoint',
            field=models.TextField(default='', help_text='', verbose_name='Get user infos url'),
        ),
        migrations.AlterField(
            model_name='userauthentication',
            name='portal_template',
            field=models.ForeignKey(help_text='Select the template to use for user authentication portal', null=True, on_delete=django.db.models.deletion.PROTECT, to='applications.PortalTemplate', verbose_name='Portal template'),
        ),
        migrations.AlterField(
            model_name='userauthentication',
            name='sso_forward_capture_content',
            field=models.TextField(default='^REGEX to capture (content.*) in SSO Forward Response$', help_text=''),
        ),
        migrations.AlterField(
            model_name='userauthentication',
            name='sso_forward_content',
            field=models.TextField(default='', help_text=''),
        ),
    ]
